window.EXTRA = window.EXTRA || {};
EXTRA.os = {
  1: [
    { q: `A user program running in user mode makes a system call, the OS services it, and control returns to the program. What sequence of mode-bit values does the hardware go through?`,
      o: [[`0 → 1 → 0`, `Reversed: in the lecture kernel mode = 0 and user mode = 1, and the program starts in user mode.`],
          [`1 → 0 → 1`, `Correct. User mode (1), the system call traps into kernel mode (0), and returning from the call resets the bit to user mode (1).`],
          [`1 → 1 → 1`, `Wrong: the system call must switch to kernel mode, otherwise privileged instructions could not be executed for the service.`],
          [`0 → 0 → 0`, `Wrong: user programs do not run with the kernel-mode bit; that would defeat dual-mode protection.`]],
      a: 1 },
    { q: `True or False: "The timer that stops a process from hogging the CPU is loaded by the user program with an ordinary (non-privileged) instruction."`,
      o: [[`True`, `Wrong: if user code could set the timer, a process could keep the CPU forever, which is exactly what the timer prevents.`],
          [`False`, `Correct. The OS sets the timer before scheduling a process, and loading it is a privileged instruction; when the counter reaches zero an interrupt returns control to the OS.`]],
      a: 1 },
    { q: `With <b>asynchronous I/O</b>, control returns to the user program without waiting. Which structure does the OS index to find a device's state and update its entry?`,
      o: [[`The interrupt vector`, `The interrupt vector holds the addresses of the interrupt service routines, not the status of each device.`],
          [`The page table`, `The page table maps pages to frames; it has nothing to do with device status.`],
          [`The device-status table`, `Correct. It holds one entry per device (type, address, state), and the OS indexes it to find and modify a device's status.`],
          [`The device controller's local buffer`, `The local buffer holds the data being transferred, not the bookkeeping about each device's state.`]],
      a: 2 },
    { q: `Which list orders the storage hierarchy correctly from <b>fastest/smallest</b> to <b>slowest/largest</b>?`,
      o: [[`Cache → registers → main memory → hard disk → solid-state disk → magnetic tape`, `Registers are faster than cache, and solid-state disks sit above (are faster than) hard disks.`],
          [`Registers → main memory → cache → solid-state disk → hard disk → optical disk`, `Cache must come before main memory: it sits between the registers and main memory.`],
          [`Registers → cache → main memory → hard disk → solid-state disk → magnetic tape`, `Solid-state disks are faster than hard disks, so SSD comes before the hard disk.`],
          [`Registers → cache → main memory → solid-state disk → hard disk → optical disk → magnetic tape`, `Correct. This is the lecture's hierarchy, organized by speed, cost and volatility.`]],
      a: 3 },
    { q: `In the I/O subsystem, <b>spooling</b> means:`,
      o: [[`Overlapping the output of one job with the input of other jobs`, `Correct. That is the lecture's definition of spooling.`],
          [`Storing data temporarily while it is being transferred`, `That is buffering, another I/O-subsystem duty.`],
          [`Storing parts of data in faster storage for performance`, `That is caching.`],
          [`Transferring a whole block from the controller to memory without the CPU`, `That is DMA, not spooling.`]],
      a: 0 },
    { q: `True or False: "Defending the system against a denial-of-service attack or a virus is an example of <b>protection</b>, as the lecture defines it."`,
      o: [[`True`, `Wrong: protection is the mechanism for controlling access of processes or users to OS-defined resources; defending against attacks is security.`],
          [`False`, `Correct. Security is defence against internal and external attacks (denial-of-service, viruses, identity theft, theft of service); protection is access control.`]],
      a: 1 },
    { q: `<b>Applied.</b> Using the lecture's units (KB = 1,024 B, MB = 1,024² B), how many bytes are in a 1.5 MB buffer?`,
      o: [[`1,500,000`, `That is the manufacturers' rounding (1 MB ≈ 1 million B), not the OS convention of 1,024² bytes.`],
          [`1,536,000`, `This mixes conventions (1.5 × 1,024 × 1,000); a MB is 1,024 × 1,024 bytes.`],
          [`1,572,864`, `Correct. 1.5 × 1,024 × 1,024 = 1.5 × 1,048,576 = 1,572,864 bytes.`],
          [`12,582,912`, `This is the number of bits (× 8). The question asks for bytes.`]],
      a: 2 },
    { q: `<b>Applied.</b> A high-speed device moves 16 KB into main memory in blocks of 1 KB. How many interrupts does the CPU receive with DMA, compared with one interrupt per byte?`,
      o: [[`16 with DMA vs 16,384 without`, `Correct. DMA raises one interrupt per block (16 blocks); one interrupt per byte would be 16 × 1,024 = 16,384.`],
          [`1 with DMA vs 16 without`, `DMA interrupts once per block, not once for the whole transfer, and "without" means per byte, not per block.`],
          [`16,384 with DMA vs 16 without`, `Reversed: DMA is what reduces interrupts to one per block.`],
          [`0 with DMA vs 16,384 without`, `DMA still interrupts the CPU once each block is done.`]],
      a: 0 },
    { q: `Which property belongs to <b>timesharing (multitasking)</b> rather than plain multiprogramming?`,
      o: [[`It keeps a subset of jobs in memory so the CPU always has one to run`, `That is the basic idea of multiprogramming (batch systems), which timesharing extends.`],
          [`Response time should be under 1 second so users can interact with each running job`, `Correct. Timesharing switches jobs so often that users can interact with them; the lecture gives a response time target of &lt; 1 second.`],
          [`One job is selected by job scheduling and runs until it must wait for I/O`, `That describes multiprogramming switching only when a job waits.`],
          [`Each processor is assigned a specific task`, `That is asymmetric multiprocessing, a hardware architecture, not timesharing.`]],
      a: 1 },
    { q: `In the lecture's "performance of the levels of storage" table, which level is managed by the <b>compiler</b>?`,
      o: [[`Cache`, `Cache is managed by hardware.`],
          [`Main memory`, `Main memory is managed by the operating system.`],
          [`Solid-state disk`, `Solid-state disks are managed by the operating system.`],
          [`Registers`, `Correct. The compiler decides which values live in registers (size &lt; 1 KB, access 0.25–0.5 ns).`]],
      a: 3 }
  ],
  2: [
    { q: `After <code>pid = fork();</code> succeeds, what value of <code>pid</code> does the <b>child</b> process see?`,
      o: [[`The child's own PID`, `The child's PID is what the parent receives, not the child.`],
          [`0`, `Correct. fork() returns 0 in the child, the child's PID in the parent, and a value &lt; 0 on error.`],
          [`The parent's PID`, `fork() does not return the parent's PID to the child.`],
          [`A negative number`, `A value &lt; 0 means fork() failed and no child was created.`]],
      a: 1 },
    { q: `<b>Applied.</b> A process runs this code (no exec, no error):<br><code>fork();<br>fork();</code><br>How many processes exist in total afterwards, including the original?`,
      o: [[`2`, `That counts only the first fork(). Both the parent and its child go on to execute the second fork().`],
          [`3`, `This adds one process per fork() call, forgetting that the first child also executes the second fork().`],
          [`4`, `Correct. The first fork() gives 2 processes; each of them runs the second fork(), giving 2 × 2 = 4.`],
          [`8`, `That would need three fork() calls (2³).`]],
      a: 2 },
    { q: `<b>Applied.</b> In the lecture's shared-memory bounded buffer, <code>BUFFER_SIZE = 8</code>, <code>in = 7</code>, <code>out = 0</code>. What does the producer do next?`,
      o: [[`It writes to buffer[7] and sets in = 0`, `It cannot: the test ((in + 1) % 8) == out is (0 == 0), so the buffer is treated as full.`],
          [`It writes to buffer[0]`, `The producer writes at index in, never at out, and anyway it must wait here.`],
          [`It busy-waits because the buffer is full (it already holds 7 items)`, `Correct. (7 + 1) % 8 = 0 = out, so the "full" loop spins. The solution only uses BUFFER_SIZE − 1 = 7 slots.`],
          [`It busy-waits because the buffer is empty`, `Empty is the consumer's test (in == out), and 7 ≠ 0.`]],
      a: 2 },
    { q: `Which scheduler removes processes from memory to disk and later brings them back (swapping), thereby <b>decreasing</b> the degree of multiprogramming?`,
      o: [[`Medium-term scheduler`, `Correct. It is added when the degree of multiprogramming must decrease and works by swapping.`],
          [`Short-term (CPU) scheduler`, `It only selects which ready process gets the CPU next, every few milliseconds.`],
          [`Long-term (job) scheduler`, `It controls the degree of multiprogramming by choosing which processes enter the ready queue; it does not swap them out.`],
          [`Dispatcher`, `The dispatcher performs the context switch for the CPU scheduler's choice; it does not swap memory images.`]],
      a: 0 },
    { q: `A running process is stopped by a timer interrupt because its time slice expired. Which state does it move to?`,
      o: [[`Waiting`, `Running → waiting happens on an I/O or event wait, not on an interrupt.`],
          [`New`, `New is only for a process being created.`],
          [`Terminated`, `It has not finished; it will run again later.`],
          [`Ready`, `Correct. In the state diagram, running → ready is labelled "interrupt"; the process waits to be dispatched again.`]],
      a: 3 },
    { q: `Which statement describes <b>indirect</b> message passing (mailboxes/ports)?`,
      o: [[`Processes must name each other explicitly: send(P, msg), receive(Q, msg)`, `That is direct communication.`],
          [`A link may connect many processes, and a pair of processes may share several links`, `Correct. A link exists only if processes share a mailbox; one link can join many processes, and a pair can share several mailboxes.`],
          [`Exactly one link exists between each pair of processes`, `That is a property of direct communication.`],
          [`Links are established automatically between every pair of processes`, `Automatic links are a property of direct communication; with mailboxes the processes must share a mailbox.`]],
      a: 1 },
    { q: `A program calls <code>malloc()</code> at run time. In which part of the process's memory is that space allocated?`,
      o: [[`Stack`, `The stack holds function parameters, return addresses and local variables, and grows down.`],
          [`Data section`, `The data section holds global and static variables, fixed before the program runs.`],
          [`Text section`, `The text section is the program code.`],
          [`Heap`, `Correct. The heap is memory dynamically allocated at run time (new, delete, malloc, free) and grows up.`]],
      a: 3 },
    { q: `Which socket refers to a service on the <b>local</b> system that uses a <b>well-known</b> port?`,
      o: [[`127.0.0.1:80`, `Correct. 127.0.0.1 is the loopback address (the local system) and port 80 is below 1024, so it is well known.`],
          [`127.0.0.1:5050`, `Loopback is right, but 5050 is not below 1024, so it is not a well-known port.`],
          [`161.25.19.8:21`, `Port 21 is well known, but 161.25.19.8 is a remote host, not the loopback address.`],
          [`161.25.19.8:1625`, `This is the lecture's remote example host, and 1625 is not a well-known port.`]],
      a: 0 },
    { q: `True or False: "During a context switch the system does useful work, because the PCBs are being updated."`,
      o: [[`True`, `Wrong: saving and loading PCBs is bookkeeping; no user process makes progress during it.`],
          [`False`, `Correct. Context-switch time is pure overhead, and it is longer when the OS and PCB are more complex.`]],
      a: 1 },
    { q: `True or False: "In the shared-memory IPC model, communication is controlled by the operating system, which also synchronizes the processes automatically."`,
      o: [[`True`, `Wrong: in shared memory, the user processes control the communication. Synchronizing them is the main problem they must solve themselves.`],
          [`False`, `Correct. Communication is under the control of the user processes, not the OS, and synchronizing their actions is the major issue.`]],
      a: 1 }
  ],
  3: [
    { q: `<b>Applied.</b> FCFS with (arrival, burst): P1 (0, 5), P2 (1, 3), P3 (2, 8), P4 (3, 2). What is the <b>average turnaround time</b>?`,
      o: [[`5.75`, `That is the average waiting time (0 + 4 + 6 + 13)/4. Turnaround also includes the burst.`],
          [`11.5`, `That is the average completion time (5 + 8 + 16 + 18)/4. You must subtract each arrival time.`],
          [`10.25`, `Correct. Gantt chart: P1 0–5, P2 5–8, P3 8–16, P4 16–18. TAT = CT − AT = 5, 7, 14, 15 → 41/4 = 10.25.`],
          [`8.5`, `That is the non-preemptive SJF average turnaround for these processes, not FCFS.`]],
      a: 2 },
    { q: `<b>Applied.</b> Non-preemptive SJF with (arrival, burst): P1 (0, 5), P2 (1, 3), P3 (2, 8), P4 (3, 2). What is the <b>average waiting time</b>?`,
      o: [[`4`, `Correct. Only P1 is there at 0, so it runs 0–5; then the shortest ready job: P4 5–7, P2 7–10, P3 10–18. WT = 0, 6, 8, 2 → 16/4 = 4.`],
          [`4.25`, `This treats all processes as arriving at 0 (P4, P2, P1, P3). The arrival times must be honoured: P4 is not there at time 0.`],
          [`5.75`, `That is the FCFS average waiting time for the same processes.`],
          [`8.5`, `That is the average turnaround time, not the waiting time.`]],
      a: 0 },
    { q: `<b>Applied.</b> SRTF (preemptive SJF) with (arrival, burst): P1 (0, 6), P2 (1, 3), P3 (2, 1), P4 (4, 2). What is the average waiting time?`,
      o: [[`3.75`, `That is non-preemptive SJF (P1 0–6, P3, P4, P2). SRTF preempts P1 when P2 arrives with a shorter burst.`],
          [`4.5`, `That is FCFS for these processes.`],
          [`5`, `That is the SRTF average turnaround time (12 + 4 + 1 + 3)/4, not the waiting time.`],
          [`2`, `Correct. P1 0–1, P2 1–2, P3 2–3, P2 3–5, P4 5–7, P1 7–12. WT = P1 6, P2 1, P3 0, P4 1 → 8/4 = 2.`]],
      a: 3 },
    { q: `<b>Applied.</b> Round Robin, q = 2, all arriving at 0 in the order P1 = 6, P2 = 3, P3 = 1. What is the average waiting time?`,
      o: [[`5`, `That is FCFS (WT 0, 6, 9). With RR, P1 is preempted after 2 units.`],
          [`4.33`, `Correct. P1 0–2, P2 2–4, P3 4–5, P1 5–7, P2 7–8, P1 8–10. WT = CT − burst = 4, 5, 4 → 13/3 ≈ 4.33.`],
          [`7.67`, `That is the average turnaround (10 + 8 + 5)/3. Subtract each burst to get the waiting time.`],
          [`1.67`, `That is SJF (P3, P2, P1), which RR does not do.`]],
      a: 1 },
    { q: `<b>Applied.</b> Non-preemptive priority (smallest number = highest priority), all at time 0. (Burst/priority): P1 4/2, P2 3/1, P3 2/4, P4 6/3. What is the <b>average turnaround time</b>?`,
      o: [[`5.75`, `That is the average waiting time (3 + 0 + 13 + 7)/4.`],
          [`8.75`, `That is FCFS order P1, P2, P3, P4, which ignores the priorities.`],
          [`9.25`, `This treats the largest number as the highest priority. In the lecture the smallest integer is the highest.`],
          [`9.5`, `Correct. Order P2 0–3, P1 3–7, P4 7–13, P3 13–15. TAT = CT = 7, 3, 15, 13 → 38/4 = 9.5.`]],
      a: 3 },
    { q: `<b>Applied.</b> Round Robin with 5 processes in the ready queue and a time quantum q = 20 ms. What is the most a process waits before its next turn on the CPU?`,
      o: [[`100 ms`, `That is n × q. The process does not wait for its own quantum, so it is (n − 1)q.`],
          [`80 ms`, `Correct. No process waits more than (n − 1)q = 4 × 20 = 80 ms.`],
          [`20 ms`, `That is one quantum, which is only true with 2 processes.`],
          [`4 ms`, `That is q / n. Each process gets 1/n of the CPU, but in chunks of q.`]],
      a: 1 },
    { q: `<b>Applied.</b> Multilevel feedback queue from the lecture: Q0 = RR with q = 8 ms, Q1 = RR with q = 16 ms, Q2 = FCFS. A new process needs a 30 ms CPU burst. How is it served?`,
      o: [[`8 ms in Q0, 16 ms in Q1, then the last 6 ms in Q2`, `Correct. It enters Q0 and gets 8 ms, is moved to Q1 for 16 ms more (24 total), and is then preempted and moved to Q2 for the remaining 6 ms.`],
          [`8 ms in Q0, then the remaining 22 ms in Q1`, `Q1's quantum is only 16 ms, so after 24 ms in total the process is demoted to Q2.`],
          [`All 30 ms in Q2, since it is longer than both quanta`, `Every new process enters Q0; it is only demoted after using up its quantum.`],
          [`16 ms in Q0, then 14 ms in Q1`, `The quanta are mixed up: Q0 has q = 8 and Q1 has q = 16.`]],
      a: 0 },
    { q: `Which scheduling criterion is <b>maximized</b>, not minimized?`,
      o: [[`Turnaround time`, `Turnaround (submission to completion) should be minimized.`],
          [`Response time`, `Response time (submission to first response) should be minimized.`],
          [`Throughput`, `Correct. Throughput, the number of processes completed per time unit, is maximized (as is CPU utilization).`],
          [`Waiting time`, `Time in the ready queue should be minimized.`]],
      a: 2 },
    { q: `True or False: "Preemptive scheduling can cause race conditions when processes share data."`,
      o: [[`True`, `Correct. A process may be preempted while updating shared data, and the next process then reads inconsistent data.`],
          [`False`, `Wrong: the lecture lists race conditions on shared data as the cost of preemption. Non-preemptive scheduling avoids this.`]],
      a: 0 },
    { q: `In a multilevel queue that prioritizes by process type, which order goes from <b>highest</b> to <b>lowest</b> priority?`,
      o: [[`Interactive → system → real-time → batch`, `Real-time processes have the highest priority, not interactive ones.`],
          [`Batch → interactive → system → real-time`, `This is reversed: batch is the lowest.`],
          [`System → real-time → batch → interactive`, `Real-time comes first, and batch is last.`],
          [`Real-time → system → interactive → batch`, `Correct. This is the lecture's prioritization by process type.`]],
      a: 3 }
  ],
  4: [
    { q: `<b>Applied.</b> A process has base register = 2000 and limit register = 500. Which user-mode address causes a trap (addressing error)?`,
      o: [[`2000`, `Legal: the check is base ≤ address, and 2000 = base.`],
          [`2250`, `Legal: 2000 ≤ 2250 &lt; 2500.`],
          [`2499`, `Legal: it is the last address before base + limit = 2500.`],
          [`2500`, `Correct. Legal addresses satisfy base ≤ address &lt; base + limit = 2500, so 2500 is outside the range and traps.`]],
      a: 3 },
    { q: `<b>Applied.</b> The MMU has relocation register = 5000 and limit register = 300. The process issues logical address 250. What happens?`,
      o: [[`Physical address 250 is accessed`, `The user's logical address is never sent to memory unchanged; the relocation value is added.`],
          [`Physical address 5250 is accessed`, `Correct. 250 &lt; 300 (limit), so physical = 250 + 5000 = 5250.`],
          [`A trap occurs, because 5250 is larger than the limit`, `The limit is compared with the logical address (250 &lt; 300), not with the physical address.`],
          [`Physical address 5300 is accessed`, `That adds the limit, not the offset: physical = logical + relocation.`]],
      a: 1 },
    { q: `<b>Applied.</b> Page size = 512 bytes. Page table: page 0 → frame 5, page 1 → frame 2, page 2 → frame 7, page 3 → frame 0. What is the physical address of logical address 1100?`,
      o: [[`3660`, `Correct. p = 1100 DIV 512 = 2, d = 1100 MOD 512 = 76; frame(2) = 7 → 7 × 512 + 76 = 3660.`],
          [`3584`, `That is the start of frame 7. The offset 76 still has to be added.`],
          [`2636`, `That uses frame 5 (page 0's frame). The page number is 2, not 0.`],
          [`1100`, `With paging the logical address is translated; it equals the physical address only if page 2 were in frame 2.`]],
      a: 0 },
    { q: `<b>Applied.</b> A logical address space has 2<sup>13</sup> bytes and the page size is 512 bytes. How are the logical address bits split?`,
      o: [[`9-bit page number, 4-bit offset`, `Reversed: the offset needs n = 9 bits to address 512 = 2⁹ bytes inside a page.`],
          [`4-bit page number, 9-bit offset`, `Correct. m = 13, n = 9: the page number is the high m − n = 4 bits (16 pages) and the offset is the low 9 bits.`],
          [`13-bit page number, 9-bit offset`, `The two fields together must equal the 13-bit address, so the page number is only 13 − 9 bits.`],
          [`4-bit page number, 13-bit offset`, `The offset only covers one page (2⁹ bytes), not the whole address space.`]],
      a: 1 },
    { q: `<b>Applied.</b> Page size = 1,024 bytes and a process needs 5,000 bytes. How many frames does it get, and how much internal fragmentation is there?`,
      o: [[`4 frames, 904 bytes`, `4 frames only hold 4,096 bytes; the remaining 904 bytes need a 5th frame. And 904 is the used part of the last page, not the waste.`],
          [`5 frames, 904 bytes`, `5 frames is right, but 904 bytes is how much of the last frame is used. The waste is 1,024 − 904.`],
          [`5 frames, 120 bytes`, `Correct. 5,000 = 4 × 1,024 + 904, so 5 frames; internal fragmentation = 1,024 − 904 = 120 bytes.`],
          [`5 frames, 0 bytes`, `Paging has no external fragmentation, but the last page usually has internal fragmentation.`]],
      a: 2 },
    { q: `<b>Applied.</b> Holes in order: 150, 400, 250, 600 KB. Processes arrive in order: 350, 200, 300 KB. Which strategy <b>fails</b> to place all three?`,
      o: [[`First-fit only`, `First-fit places 350 → 400, 200 → 250, 300 → 600: all placed.`],
          [`Best-fit only`, `Best-fit places 350 → 400, 200 → 250, 300 → 600: all placed.`],
          [`None of them; all three strategies place every process`, `Worst-fit runs out of a big enough hole for the 300 KB process.`],
          [`Worst-fit only`, `Correct. 350 → 600 (250 left), 200 → 400 (200 left); the holes are now 150, 200, 250, 250, so 300 KB must wait.`]],
      a: 3 },
    { q: `<b>Applied.</b> A segment table has STLR = 4. Segment 3 has base 900 and limit 200. Which logical address is translated <b>without</b> a trap?`,
      o: [[`(4, 10)`, `Segment number 4 is not legal: s must be &lt; STLR = 4, so this traps even though the offset is small.`],
          [`(3, 150) → physical 1050`, `Correct. s = 3 &lt; 4 and d = 150 &lt; 200, so physical = 900 + 150 = 1050.`],
          [`(3, 200) → physical 1100`, `The offset must be strictly less than the limit; 200 is not &lt; 200, so it traps.`],
          [`(3, 250) → physical 1150`, `250 ≥ limit 200, so this is an addressing error.`]],
      a: 1 },
    { q: `At which address-binding stage is <b>absolute code</b> produced, so the program must be recompiled if its start location changes?`,
      o: [[`Compile time`, `Correct. If the memory location is known a priori, the compiler generates absolute code; changing the start location means recompiling.`],
          [`Load time`, `Load-time binding generates relocatable code, because the location is not known at compile time.`],
          [`Execution time`, `Execution-time binding delays binding until run time, so the process can even move while running.`],
          [`Link time with dynamic loading`, `Dynamic loading is about loading a routine only when it is called; it is not a binding stage that produces absolute code.`]],
      a: 0 },
    { q: `True or False: "Compaction can be used to reduce external fragmentation only if relocation is dynamic and done at execution time."`,
      o: [[`True`, `Correct. Compaction moves processes in memory, which is only possible when their addresses are bound at execution time.`],
          [`False`, `Wrong: with compile-time or load-time binding a process cannot be moved, so compaction is not possible.`]],
      a: 0 },
    { q: `True or False: "Dynamic loading needs special support from the operating system to work."`,
      o: [[`True`, `Wrong: the lecture says dynamic loading needs no special OS support; the OS may only help by providing libraries.`],
          [`False`, `Correct. It is implemented through program design: a routine is loaded only when it is called. The OS can help by providing libraries.`]],
      a: 1 }
  ],
  5: [
    { q: `<b>Applied.</b> Reference string 1, 3, 0, 3, 5, 6, 3, 1, 0, 2 with <b>3 frames</b>, initially empty. How many page faults does <b>FIFO</b> cause?`,
      o: [[`7`, `That is the Optimal count for this string.`],
          [`8`, `That is the LRU count. FIFO evicts by load time and throws out page 3 just before it is needed again.`],
          [`10`, `This counts every reference. The second reference to 3 (position 4) is a hit.`],
          [`9`, `Correct. Faults on 1, 3, 0, (3 hit), 5 (evict 1), 6 (evict 3), 3 (evict 0), 1 (evict 5), 0 (evict 6), 2 (evict 3) = 9.`]],
      a: 3 },
    { q: `<b>Applied.</b> Same string 1, 3, 0, 3, 5, 6, 3, 1, 0, 2 with 3 frames. How many page faults does <b>LRU</b> cause?`,
      o: [[`8`, `Correct. 1, 3, 0 fault; 3 hit; 5 evicts 1; 6 evicts 0; 3 hit; 1 evicts 5; 0 evicts 6; 2 evicts 3 → 8 faults.`],
          [`9`, `That is FIFO. LRU keeps page 3 because it was used recently, so the 7th reference is a hit.`],
          [`7`, `That is Optimal, which looks into the future; LRU only uses the past.`],
          [`6`, `This leaves out the 3 faults that fill the empty frames at the start. They count as faults.`]],
      a: 0 },
    { q: `<b>Applied.</b> Same string 1, 3, 0, 3, 5, 6, 3, 1, 0, 2 with 3 frames. How many page faults does <b>Optimal</b> cause?`,
      o: [[`8`, `That is LRU. When 5 arrives, Optimal evicts 0 (used farthest in the future), not 1.`],
          [`9`, `That is FIFO.`],
          [`7`, `Correct. 1, 3, 0 fault; 3 hit; 5 evicts 0 (next used last); 6 evicts 5 (never used again); 3 and 1 hit; 0 and 2 fault → 7.`],
          [`4`, `This forgets the initial fills: the first 3 references to empty frames are faults too.`]],
      a: 2 },
    { q: `<b>Applied.</b> Second-chance (clock) algorithm. The FIFO order (oldest first) with reference bits is: A (1), B (1), C (0), D (1). A page must be replaced. Which page is the victim?`,
      o: [[`A, because it is the oldest`, `A's bit is 1, so it gets a second chance: its bit is cleared and it stays.`],
          [`D, because it was loaded last`, `The algorithm starts from the oldest page, and D's bit is 1 anyway.`],
          [`C`, `Correct. A and B have bit 1, so each is set to 0 and skipped; C has bit 0, so it is replaced.`],
          [`B, after A's bit is cleared`, `B's bit is also 1, so it also gets a second chance.`]],
      a: 2 },
    { q: `<b>Applied.</b> Pages in memory with reference counts: P = 5, Q = 2, R = 9. Which page does <b>MFU</b> replace, and which does <b>LFU</b> replace?`,
      o: [[`MFU replaces Q, LFU replaces R`, `Reversed: LFU removes the smallest count and MFU the largest.`],
          [`MFU replaces R, LFU replaces Q`, `Correct. MFU removes the largest count (R = 9); LFU removes the smallest count (Q = 2).`],
          [`Both replace Q`, `Only LFU picks the smallest count. MFU argues the smallest-count page was probably just brought in.`],
          [`Both replace R`, `Only MFU picks the largest count.`]],
      a: 1 },
    { q: `In the basic page-fault handling, after the page has been read into a free frame, what are the last two steps?`,
      o: [[`Restart the instruction, then set the validation bit to v`, `The order is wrong: the tables must show the page is in memory before the instruction is restarted, or it would fault again.`],
          [`Abort the process, then free the frame`, `Abort only happens for an invalid reference, found in step 1.`],
          [`Set the validation bit to i, then restart the instruction`, `i means "not in memory". After loading, the bit must be set to v.`],
          [`Reset the tables (validation bit = v), then restart the instruction that caused the fault`, `Correct. These are steps 4 and 5 of the lecture's page-fault handling.`]],
      a: 3 },
    { q: `True or False: "LRU can suffer from Belady's anomaly, just like FIFO."`,
      o: [[`True`, `Wrong: the lecture states LRU and OPT are stack algorithms and never suffer from Belady's anomaly.`],
          [`False`, `Correct. Belady's anomaly (more frames → more faults) affects FIFO. LRU and OPT are stack algorithms and are immune.`]],
      a: 1 },
    { q: `True or False: "When counting page faults on a reference string, loading a page into an empty frame at the start does not count as a fault."`,
      o: [[`True`, `Wrong: every empty-frame fill at the start is also a page fault, because the page was not in memory.`],
          [`False`, `Correct. The lecture counts every initial fill as a fault; only repeated access to a page already in memory is not a fault.`]],
      a: 1 },
    { q: `What is the trade-off of the <b>stack</b> implementation of LRU?`,
      o: [[`Each reference is more expensive (up to 6 pointer changes), but no search is needed to find the victim`, `Correct. The referenced page moves to the top of a doubly-linked stack, and the LRU page is always at the bottom.`],
          [`Each reference only copies the clock, but replacement needs a search for the smallest counter`, `That is the counter implementation.`],
          [`It needs no hardware help and is identical to FIFO`, `A stack ordered by recent use is LRU, not FIFO; FIFO orders by load time.`],
          [`It only knows which pages were referenced, not in which order`, `That is the limitation of the single reference bit.`]],
      a: 0 },
    { q: `In the worst-case stages of demand paging, what does the OS do while the process waits for its page to be read from disk?`,
      o: [[`Busy-waits until the disk transfer completes`, `Wasteful: the lecture's stage 6 gives the CPU to another user during the wait.`],
          [`Allocates the CPU to some other user`, `Correct. Stage 6: while waiting, allocate the CPU to some other user; the disk interrupt (stage 7) signals completion later.`],
          [`Restarts the faulting instruction right away`, `The instruction can only be restarted after the page is in memory and the tables are corrected.`],
          [`Terminates the process to free its frames`, `A legal page fault is a normal event; the process is resumed, not terminated.`]],
      a: 1 }
  ],
  6: [
    { q: `<b>Applied.</b> Use this snapshot (resources A B C, totals A = 6, B = 4, C = 5):<br><table><tr><th>Process</th><th>Allocation</th><th>Max</th></tr><tr><td>P0</td><td>1 0 1</td><td>3 2 2</td></tr><tr><td>P1</td><td>2 1 0</td><td>2 2 1</td></tr><tr><td>P2</td><td>0 1 1</td><td>4 1 3</td></tr><tr><td>P3</td><td>1 1 0</td><td>1 3 2</td></tr></table>What is the <b>Need</b> of P2?`,
      o: [[`(4, 2, 4)`, `This adds Allocation to Max. Need = Max − Allocation.`],
          [`(4, 0, 2)`, `Correct. (4, 1, 3) − (0, 1, 1) = (4, 0, 2).`],
          [`(4, 1, 3)`, `That is P2's Max. It already holds (0, 1, 1), which must be subtracted.`],
          [`(−4, 0, −2)`, `The subtraction is reversed (Allocation − Max).`]],
      a: 1 },
    { q: `<b>Applied.</b> Same snapshot (totals A = 6, B = 4, C = 5; Allocation P0 1 0 1, P1 2 1 0, P2 0 1 1, P3 1 1 0). What is the <b>Available</b> vector?`,
      o: [[`(4, 3, 2)`, `That is the sum of the Allocation columns. Available = Total − that sum.`],
          [`(6, 4, 5)`, `Those are the totals; some instances are already allocated.`],
          [`(2, 1, 3)`, `Correct. (6, 4, 5) − (4, 3, 2) = (2, 1, 3).`],
          [`(2, 2, 1)`, `That is P0's Need, not the Available vector.`]],
      a: 2 },
    { q: `<b>Applied.</b> Same snapshot: Available = (2, 1, 3); Need P0 (2, 2, 1), P1 (0, 1, 1), P2 (4, 0, 2), P3 (0, 2, 2). Which is a <b>safe sequence</b>?`,
      o: [[`&lt;P0, P1, P2, P3&gt;`, `P0 cannot go first: it needs 2 of B but only 1 is available.`],
          [`&lt;P2, P1, P3, P0&gt;`, `P2 cannot go first: it needs 4 of A but only 2 are available.`],
          [`&lt;P3, P1, P2, P0&gt;`, `P3 cannot go first: it needs 2 of B but only 1 is available.`],
          [`&lt;P1, P2, P3, P0&gt;`, `Correct. P1 → Work (4, 2, 3); P2 → (4, 3, 4); P3 → (5, 4, 4); P0 → (6, 4, 5). Everyone finishes, so the state is safe.`]],
      a: 3 },
    { q: `<b>Applied.</b> Same snapshot (Available (2, 1, 3)). P0 now requests (1, 1, 0). What does the banker's algorithm decide?`,
      o: [[`Grant it, because the request ≤ Need and ≤ Available`, `Those checks pass, but the pretend state must also be safe, and it is not.`],
          [`Error, because the request exceeds P0's maximum claim`, `Request (1, 1, 0) ≤ Need (2, 2, 1), so it does not exceed the claim.`],
          [`P0 must wait: the pretend state is unsafe`, `Correct. Pretend: Available (1, 0, 3), Need P0 (1, 1, 1). With B = 0, no process (P0, P1, P3 all need B; P2 needs 4 A) can finish, so the old state is restored and P0 waits.`],
          [`Grant it, because the system was safe before the request`, `Safety must be checked on the new state after the pretend allocation, not on the old one.`]],
      a: 2 },
    { q: `<b>Applied.</b> Detection algorithm, resources A B, Available (0, 0).<br>Allocation: P0 (1, 0), P1 (1, 1), P2 (1, 1). Request: P0 (0, 1), P1 (1, 0), P2 (0, 0).<br>What is the result?`,
      o: [[`No deadlock: &lt;P2, P0, P1&gt; can finish`, `Correct. P2 requests nothing → Work (1, 1); P0 (0, 1) ✓ → (2, 1); P1 (1, 0) ✓ → (3, 2). All Finish = true.`],
          [`P0 and P1 are deadlocked`, `They would be stuck only if P2 never released its resources; P2's request is (0, 0), so it finishes first.`],
          [`All three are deadlocked, since Available is (0, 0)`, `Available = 0 does not mean deadlock: a process with Request ≤ Work (P2) can still finish and release.`],
          [`Only P2 is deadlocked`, `P2 needs nothing more, so it is the first to finish.`]],
      a: 0 },
    { q: `True or False: "If a resource-allocation graph contains a cycle, the system is definitely deadlocked."`,
      o: [[`True`, `Wrong: only with a single instance per resource type. With several instances a cycle means only a possibility (the lecture's P2/P4 example).`],
          [`False`, `Correct. A cycle with several instances per type only means deadlock is possible; e.g. P2 and P4 can release and break the cycle.`]],
      a: 1 },
    { q: `<b>Applied.</b> Circular-wait prevention with F(tape drive) = 1, F(disk drive) = 5, F(printer) = 12. A process already holds the <b>disk drive</b>. Which request is allowed next?`,
      o: [[`The tape drive`, `F(tape) = 1 &lt; 5. Requests must be in increasing order, so it cannot ask for the tape while holding the disk.`],
          [`The tape drive and the printer together`, `The tape part still breaks the increasing order.`],
          [`Any resource, as long as it is free`, `Then circular wait would not be prevented. Requests must follow the total ordering.`],
          [`The printer`, `Correct. F(printer) = 12 > F(disk) = 5, so the request is in increasing order of enumeration.`]],
      a: 3 },
    { q: `To prevent the <b>no-preemption</b> condition, a process that cannot get a resource releases everything it holds. To which resources does this approach apply?`,
      o: [[`Resources whose state is easily saved and restored, such as CPU registers and memory space`, `Correct. The lecture limits this method to such resources.`],
          [`Non-sharable resources such as printers in the middle of a job`, `Taking a printer in mid-job cannot be undone cleanly; its state is not easily saved.`],
          [`Only read-only files`, `Read-only files are sharable, which is about mutual exclusion, not preemption.`],
          [`Every resource type in the system`, `The lecture restricts it to resources whose state can be saved and restored.`]],
      a: 0 },
    { q: `True or False: "Searching a wait-for graph with n vertices for a cycle costs O(n²) operations."`,
      o: [[`True`, `Correct. The lecture gives O(n²) for cycle detection in the wait-for graph (single instance of each resource type).`],
          [`False`, `Wrong: the lecture states cycle detection requires O(n²) operations for n vertices.`]],
      a: 0 },
    { q: `In recovery by resource preemption, how does the system stop the same process from always being chosen as the victim?`,
      o: [[`It aborts all deadlocked processes at once`, `That is recovery by process termination, not a fix for victim starvation.`],
          [`It rolls the victim back to the very beginning every time`, `Rollback is a separate issue; it does not stop the same victim being picked again.`],
          [`It includes the number of rollbacks in the cost factor`, `Correct. Counting rollbacks in the cost stops the same process from starving.`],
          [`It uses aging on the CPU priority`, `Aging is the solution to starvation in CPU scheduling (Lecture 3), not the one given for victim selection.`]],
      a: 2 }
  ],
  7: [
    { q: `<b>Applied.</b> After <code>chmod 754 notes</code>, what may the <b>group</b> do with the file?`,
      o: [[`Read, write and execute`, `That is 7 = 111, the owner's rights.`],
          [`Read only`, `That is 4 = 100, the public's rights.`],
          [`Read and execute`, `Correct. Group = 5 = 101 = R-X.`],
          [`Read and write`, `That would be 6 = 110, but the group digit here is 5.`]],
      a: 2 },
    { q: `<b>Applied.</b> A file should give the owner read and write, the group read only, and the public nothing. Which chmod value is this?`,
      o: [[`640`, `Correct. Owner RW- = 110 = 6, group R-- = 100 = 4, public --- = 000 = 0.`],
          [`620`, `2 = 010 is write only, not read only, for the group.`],
          [`460`, `The digits are in the order owner, group, public; here the owner and group are swapped.`],
          [`750`, `7 gives the owner execute too, and 5 gives the group execute.`]],
      a: 0 },
    { q: `<b>Applied.</b> With contiguous allocation, a directory entry for file <code>data</code> says start = 20, length = 5. Which disk block holds the <b>4th</b> block of the file?`,
      o: [[`24`, `Off by one: the blocks are 20, 21, 22, 23, 24, so 24 is the 5th (last) block.`],
          [`3`, `That is the block's position inside the file. It must be added to the start block.`],
          [`25`, `25 is past the end of the file (start + length).`],
          [`23`, `Correct. The file occupies 20–24; the 4th block is start + 3 = 23. This easy direct access is why contiguous allocation performs well.`]],
      a: 3 },
    { q: `<b>Applied.</b> In a FAT volume, a directory entry has start block 5. FAT[5] = 12, FAT[12] = 3, FAT[3] = −1. Which is true?`,
      o: [[`The file has 2 blocks and ends at block 12`, `The chain does not stop at 12: FAT[12] points to block 3.`],
          [`The file has 3 blocks, 5 → 12 → 3, and block 3 is the last`, `Correct. Follow the links from the start block; −1 marks the end of file at block 3.`],
          [`The file has 4 blocks, including block −1`, `−1 is the end-of-file marker, not a block.`],
          [`The file occupies blocks 3 to 12 contiguously`, `FAT is a variant of linked allocation; the blocks can be scattered anywhere.`]],
      a: 1 },
    { q: `<b>Applied.</b> Sequential access is simulated on a direct-access file with a current position <code>cp</code>. Right now cp = 4 and a <b>read next</b> is issued. What happens?`,
      o: [[`Block 5 is read and cp becomes 5`, `It reads at the current position before it increments cp.`],
          [`Block 4 is read and cp stays 4`, `read next also does cp = cp + 1.`],
          [`cp is reset to 0, then block 0 is read`, `Setting cp = 0 is what reset does, not read next.`],
          [`Block 4 is read and cp becomes 5`, `Correct. read next → read cp; cp = cp + 1.`]],
      a: 3 },
    { q: `What does the <b>open(F<sub>i</sub>)</b> operation do?`,
      o: [[`It searches the directory on disk for entry F<sub>i</sub> and moves its content to memory`, `Correct. This is the lecture's definition; close(F<sub>i</sub>) moves the in-memory entry back to the directory on disk.`],
          [`It copies the whole file's data blocks into main memory`, `open brings in the directory entry, not all the file's data.`],
          [`It moves the in-memory entry back to the directory on disk`, `That is close(F<sub>i</sub>).`],
          [`It creates a new empty file named F<sub>i</sub>`, `That is the create operation.`]],
      a: 0 },
    { q: `What is the <b>file-open count</b> used for?`,
      o: [[`To record the last read/write location for each process`, `That is the file pointer.`],
          [`To store each process's access mode`, `That is the access-rights information.`],
          [`To count how many times the file has been opened, so its open-file-table entry can be removed when the last process closes it`, `Correct. When the count drops to zero, the entry can be removed from the open-file table.`],
          [`To count the number of blocks allocated to the file`, `That is the file's size/location information, not open-file data.`]],
      a: 2 },
    { q: `Compared with a single-level directory, what does a <b>two-level directory</b> (one UFD per user) fix, and what problem remains?`,
      o: [[`It fixes grouping, but users still need unique names`, `It is the other way round: naming is fixed and grouping is not.`],
          [`It fixes naming (different users can use the same file name), but there is still no grouping within a user`, `Correct. Files are addressed as user/file, so names only need to be unique per user; grouping needs a tree structure.`],
          [`It fixes both naming and grouping`, `A user still cannot group their own files; that needs a tree-structured directory.`],
          [`It fixes nothing; it only makes searching slower`, `Searching becomes efficient, and the naming problem across users is solved.`]],
      a: 1 },
    { q: `True or False: "In a tree-structured directory, deleting the directory <code>mail</code> deletes the entire subtree rooted at <code>mail</code>."`,
      o: [[`True`, `Correct. The lecture states that deleting "mail" deletes the whole subtree rooted at mail.`],
          [`False`, `Wrong: in the lecture's tree example, deleting a directory removes everything under it.`]],
      a: 0 },
    { q: `True or False: "With linked allocation, the size of a file must be declared when it is created."`,
      o: [[`True`, `Wrong: knowing the size in advance is a problem of contiguous allocation. Linked files grow block by block.`],
          [`False`, `Correct. Linked allocation has no external fragmentation, needs no compaction and does not need the size at creation.`]],
      a: 1 }
  ],
  8: [
    { q: `<b>Applied.</b> In the six-step DMA process, the driver asks for C = 2,048 bytes to go into a buffer at address X. After the DMA controller has moved 500 bytes, what are C and the next memory address?`,
      o: [[`C = 2,048, next address X`, `The DMA controller updates both values after every byte it transfers.`],
          [`C = 500, next address X + 1,548`, `The values are swapped: 500 bytes are done, so 1,548 remain and the address has moved forward by 500.`],
          [`C = 1,548, next address X + 500`, `Correct. The DMA controller increases the memory address and decreases C for each byte, until C = 0.`],
          [`C = 1,548, next address X − 500`, `The memory address increases, not decreases.`]],
      a: 2 },
    { q: `Which item is <b>not</b> part of the DMA command block that the OS writes into memory?`,
      o: [[`Source and destination addresses`, `This is part of the command block.`],
          [`The PCB of the process that requested the I/O`, `Correct. The command block holds the source and destination addresses, read/write mode and byte count; the PCB is not in it.`],
          [`Read or write mode`, `This is part of the command block.`],
          [`Count of bytes`, `This is part of the command block.`]],
      a: 1 },
    { q: `<b>Applied.</b> Using the lecture's PC I/O port table, which device answers at port address <b>3FA</b>?`,
      o: [[`Diskette-drive controller`, `It uses 3F0–3F7, which ends just before 3FA.`],
          [`Serial port (secondary)`, `The secondary serial port is 2F8–2FF.`],
          [`Graphics controller`, `The graphics controller is 3D0–3DF.`],
          [`Serial port (primary)`, `Correct. The primary serial port uses 3F8–3FF, and 3FA is inside that range.`]],
      a: 3 },
    { q: `In the Intel Pentium event-vector table, what do vectors <b>32–255</b> hold?`,
      o: [[`Maskable interrupts`, `Correct. 0–31 are specific events (divide error, page fault…) or reserved; 32–255 are maskable interrupts.`],
          [`Page faults`, `A page fault is the single vector 14.`],
          [`Reserved entries`, `15 and 19–31 are reserved; 32–255 are used.`],
          [`Divide errors`, `Divide error is vector 0.`]],
      a: 0 },
    { q: `In the polling handshake, after the host sets the <b>command-ready</b> bit, what happens next?`,
      o: [[`The host reads the busy bit until it becomes 0`, `That is step 1, done before the host sets command-ready.`],
          [`The controller raises an interrupt on the Interrupt Request Line`, `Polling does not use interrupts; the host keeps checking the status register.`],
          [`The controller sets the busy bit and executes the transfer`, `Correct. Step 4: the controller sees command-ready, sets busy and does the transfer; in step 5 it clears busy, error and command-ready.`],
          [`The host copies the data into the data-out register`, `For a write this is done in step 2, before command-ready is set.`]],
      a: 2 },
    { q: `In the polling handshake, the host repeatedly checks the busy bit. Which device register is it reading?`,
      o: [[`Data-in`, `Data-in holds data the host reads from the device.`],
          [`Data-out`, `Data-out holds data the host writes to the device.`],
          [`Control`, `The control register is for commands from the host; the busy bit the host polls is reported elsewhere.`],
          [`Status`, `Correct. The busy (and error) bits are in the status register.`]],
      a: 3 },
    { q: `Which pair matches a device class with the commands the lecture lists for it?`,
      o: [[`Block devices (disk drives): read, write, seek. Character devices (keyboard, mouse): get(), put()`, `Correct. Block devices also allow raw I/O, memory-mapped file access and DMA; character devices can have line editing layered on top.`],
          [`Block devices: get(), put(). Character devices: read, write, seek`, `Reversed: seek only makes sense for random-access block devices such as disks.`],
          [`Both classes use only get() and put()`, `Disk drives use read, write and seek.`],
          [`Character devices are disk drives; block devices are keyboards`, `Reversed: keyboards, mice and serial ports are character devices; disk drives are block devices.`]],
      a: 0 },
    { q: `In the typical PC bus figure, which bus connects relatively <b>slow</b> devices such as the keyboard and the serial and parallel ports?`,
      o: [[`The PCI bus`, `PCI connects the graphics, SCSI and IDE controllers; slow devices hang off the expansion bus behind it.`],
          [`The memory bus through the bridge/memory controller`, `That links the processor and memory, not the keyboard or ports.`],
          [`The expansion bus`, `Correct. The expansion bus interface on the PCI bus connects the keyboard and the parallel and serial ports.`],
          [`The SCSI bus`, `The SCSI controller connects disks.`]],
      a: 2 },
    { q: `True or False: "When it finishes, the interrupt handler performs a state restore and executes a return-from-interrupt instruction so the CPU returns to its previous state."`,
      o: [[`True`, `Correct. The handler determines the cause, does the necessary processing, restores state and returns from the interrupt.`],
          [`False`, `Wrong: this is exactly how the lecture says the interrupt handler ends.`]],
      a: 0 },
    { q: `True or False: "Polling is always more efficient than interrupts, whatever the speed of the device."`,
      o: [[`True`, `Wrong: busy-waiting wastes the CPU on slow devices. That is why the controller notifying the CPU (an interrupt) is sometimes more efficient.`],
          [`False`, `Correct. Polling is reasonable for fast devices but inefficient for slow ones; interrupts let the device notify the CPU instead.`]],
      a: 1 }
  ]
};
